### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by sandgate-dev** [learn-co-curriculum/dsc-0-02-12-functions-with-arguments-lab#1]
Not that I want to complain about it, but all the work was already done for me (us I guess).

Very much appreciate it.

**Comment by PeterBell** [comment]
Looks like @tkoar fixed with https://github.com/learn-co-curriculum/dsc-1-02-12-functions-with-arguments-lab/commit/63beabe5c1041777dc0cd70e7a7b06b6d414b8e4 - thanks for catching this Stephan!
