### ISSUE TITLE
Median function incorrect

### ISSUE THREAD

**Issue by DanyalAndriano** [learn-co-curriculum/dsc-0-02-12-functions-with-arguments-lab#3]
Just eyeing the ordered list: [350, 604, 1200, 1369, 1588, 2455]
The median should be the average of the middle values: (1200 + 1369)/2 = 1284.5

However, the answer in the pytest is 1394.0.
I think this is because the solution code does not seem to take order into account when accessing the dict values directly.

**Comment by PeterBell** [comment]
Thanks for catching - actually looks like the median given in PyTest was just for the 4 new restaurants. Fixed now with https://github.com/learn-co-curriculum/dsc-1-02-12-functions-with-arguments-lab/commit/6db7f0bd9b4edb2c430c7fdc05541fdfe8ac905d - thanks @DanyalAndriano !
